# Generated by Django 5.0.7 on 2026-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('strategy_selection', 'Strategy Selection'), ('intervention_trigger', 'Intervention Trigger'), ('goal_adjustment', 'Goal Adjustment'), ('milestone_suggestion', 'Milestone Suggestion'), ('recovery_plan', 'Recovery Plan'), ('encouragement', 'Encouragement')], max_length=50)),
                ('context', models.JSONField()),
                ('user_state', models.JSONField()),
                ('decision', models.TextField()),
                ('rationale', models.TextField()),
                ('reasoning_steps', models.JSONField(default=list)),
                ('alternatives_considered', models.JSONField(default=list)),
                ('confidence_score', models.FloatField()),
                ('risk_assessment', models.JSONField(default=dict)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('opik_trace_id', models.CharField(blank=True, max_length=255)),
                ('opik_span_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hypothesis', models.TextField()),
                ('variants', models.JSONField()),
                ('allocation', models.JSONField()),
                ('success_metrics', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('winner', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_experiments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_implemented', models.BooleanField(default=False)),
                ('user_satisfaction', models.IntegerField(blank=True, null=True)),
                ('effectiveness_score', models.FloatField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField()),
                ('user_feedback', models.TextField(blank=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('control_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_performance_metrics',
            },
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=100)),
                ('insight_description', models.TextField()),
                ('supporting_data', models.JSONField()),
                ('confidence', models.FloatField()),
                ('applied_to_decisions', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_method', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
