# Generated by Django 5.0.7 on 2026-01-17 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdecision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentperformancemetric',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.agentdecision'),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentdecision',
            index=models.Index(fields=['user', '-created_at'], name='agent_decis_user_id_4ddf77_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdecision',
            index=models.Index(fields=['decision_type', '-created_at'], name='agent_decis_decisio_d369e3_idx'),
        ),
    ]
