# Generated by Django 5.0.7 on 2026-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('is_on_track', models.BooleanField(default=True)),
                ('predicted_completion_date', models.DateField(blank=True, null=True)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('success_likelihood', models.FloatField(default=0.5)),
                ('current_strategy', models.JSONField(blank=True, default=dict)),
                ('strategy_adjustments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['order', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('progress_percentage', models.IntegerField()),
                ('mood', models.CharField(choices=[('motivated', 'Motivated'), ('neutral', 'Neutral'), ('struggling', 'Struggling'), ('frustrated', 'Frustrated'), ('confident', 'Confident')], default='neutral', max_length=20)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('key_insights', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'progress_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('setback_type', models.CharField(max_length=100)),
                ('root_causes', models.JSONField(blank=True, default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_strategy', models.TextField(blank=True)),
                ('recovery_actions', models.JSONField(blank=True, default=list)),
                ('ai_recovery_plan', models.JSONField(blank=True, default=dict)),
                ('similar_past_setbacks', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'setbacks',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
