# Generated by Django 5.0.7 on 2026-01-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('check_in', 'Check-in'), ('goal_setting', 'Goal Setting'), ('setback_recovery', 'Setback Recovery'), ('strategy_adjustment', 'Strategy Adjustment'), ('celebration', 'Celebration'), ('reflection', 'Reflection')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('user_state', models.JSONField(blank=True, default=dict)),
                ('outcome_summary', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('insights_gained', models.JSONField(blank=True, default=list)),
                ('agent_confidence', models.FloatField(default=0.0)),
                ('reasoning_chain', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coaching_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('applicable_situations', models.JSONField(blank=True, default=list)),
                ('user_personas', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('success_rate', models.FloatField(default=0.0)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coaching_strategies',
                'ordering': ['-success_rate'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('motivational', 'Motivational'), ('corrective', 'Corrective'), ('supportive', 'Supportive'), ('challenging', 'Challenging'), ('informational', 'Informational')], max_length=50)),
                ('trigger_reason', models.TextField()),
                ('message', models.TextField()),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('decision_reasoning', models.TextField()),
                ('confidence_level', models.FloatField()),
                ('alternative_approaches', models.JSONField(blank=True, default=list)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reasoning', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
